<?php

namespace Database\Seeders;

use App\Domains\Company\Models\Permission;
use App\Domains\Company\Models\Role;
use Illuminate\Database\Seeder;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            ['name' => 'View users', 'slug' => 'users.view', 'module' => 'users'],
            ['name' => 'Manage users', 'slug' => 'users.manage', 'module' => 'users'],
            ['name' => 'Create users', 'slug' => 'users.create', 'module' => 'users'],
            ['name' => 'Update users', 'slug' => 'users.update', 'module' => 'users'],
            ['name' => 'Deactivate users', 'slug' => 'users.deactivate', 'module' => 'users'],
            ['name' => 'Reset user password', 'slug' => 'users.reset_password', 'module' => 'users'],
            ['name' => 'Manage user permissions', 'slug' => 'users.manage_permissions', 'module' => 'users'],
            ['name' => 'View dashboard', 'slug' => 'dashboard.view', 'module' => 'dashboard'],
            ['name' => 'View team dashboard', 'slug' => 'dashboard.team', 'module' => 'dashboard'],
            ['name' => 'Manage company', 'slug' => 'company.manage', 'module' => 'company'],
            ['name' => 'Manage branding', 'slug' => 'branding.manage', 'module' => 'branding'],
            ['name' => 'View onboarding', 'slug' => 'onboarding.view', 'module' => 'onboarding'],
            ['name' => 'Manage onboarding', 'slug' => 'onboarding.manage', 'module' => 'onboarding'],
            ['name' => 'View reports', 'slug' => 'reports.view', 'module' => 'reports'],
            ['name' => 'View campaigns', 'slug' => 'campaigns.view', 'module' => 'campaigns'],
            ['name' => 'Manage campaigns', 'slug' => 'campaigns.manage', 'module' => 'campaigns'],
            ['name' => 'View visits', 'slug' => 'visits.view', 'module' => 'visits'],
            ['name' => 'Manage visits', 'slug' => 'visits.manage', 'module' => 'visits'],
            ['name' => 'View cities', 'slug' => 'cities.view', 'module' => 'territory'],
            ['name' => 'Manage cities', 'slug' => 'cities.manage', 'module' => 'territory'],
            ['name' => 'View sectors', 'slug' => 'sectors.view', 'module' => 'territory'],
            ['name' => 'Manage sectors', 'slug' => 'sectors.manage', 'module' => 'territory'],
            ['name' => 'View properties', 'slug' => 'properties.view', 'module' => 'properties'],
            ['name' => 'Manage properties', 'slug' => 'properties.manage', 'module' => 'properties'],
            ['name' => 'View residents', 'slug' => 'residents.view', 'module' => 'residents'],
            ['name' => 'Manage residents', 'slug' => 'residents.manage', 'module' => 'residents'],
            ['name' => 'View maps', 'slug' => 'maps.view', 'module' => 'maps'],
            ['name' => 'Manage maps', 'slug' => 'maps.manage', 'module' => 'maps'],
            ['name' => 'Access sales app', 'slug' => 'sales_app.access', 'module' => 'sales_app'],
            ['name' => 'View training', 'slug' => 'training.view', 'module' => 'training'],
            ['name' => 'Manage training', 'slug' => 'training.manage', 'module' => 'training'],
            ['name' => 'View communication', 'slug' => 'communication.view', 'module' => 'communication'],
            ['name' => 'Manage communication', 'slug' => 'communication.manage', 'module' => 'communication'],
            ['name' => 'Access AI', 'slug' => 'ai.access', 'module' => 'ai'],
            ['name' => 'Manage AI', 'slug' => 'ai.manage', 'module' => 'ai'],
            ['name' => 'View billing', 'slug' => 'billing.view', 'module' => 'billing'],
            ['name' => 'Manage billing', 'slug' => 'billing.manage', 'module' => 'billing'],
            ['name' => 'Access platform', 'slug' => 'platform.access', 'module' => 'platform'],
            ['name' => 'Manage platform companies', 'slug' => 'platform.companies.manage', 'module' => 'platform'],
            ['name' => 'Manage platform plans', 'slug' => 'platform.plans.manage', 'module' => 'platform'],
            ['name' => 'Impersonate users', 'slug' => 'platform.impersonate', 'module' => 'platform'],
            ['name' => 'Manage feature flags', 'slug' => 'platform.feature_flags.manage', 'module' => 'platform'],
            ['name' => 'View health scores', 'slug' => 'platform.health.view', 'module' => 'platform'],
            ['name' => 'View audit logs', 'slug' => 'audit.view', 'module' => 'audit'],
            ['name' => 'View privacy', 'slug' => 'privacy.view', 'module' => 'privacy'],
            ['name' => 'Manage privacy', 'slug' => 'privacy.manage', 'module' => 'privacy'],
            ['name' => 'View CRM', 'slug' => 'crm.view', 'module' => 'crm'],
            ['name' => 'Manage CRM', 'slug' => 'crm.manage', 'module' => 'crm'],
            ['name' => 'View integrations', 'slug' => 'integrations.view', 'module' => 'integrations'],
            ['name' => 'Manage integrations', 'slug' => 'integrations.manage', 'module' => 'integrations'],
            ['name' => 'Create property point', 'slug' => 'properties.create', 'module' => 'properties'],
            ['name' => 'Update property point', 'slug' => 'properties.update', 'module' => 'properties'],
            ['name' => 'Adjust property location', 'slug' => 'properties.adjust', 'module' => 'properties'],
            ['name' => 'Delete property point', 'slug' => 'properties.delete', 'module' => 'properties'],
            ['name' => 'Edit property notes', 'slug' => 'properties.notes', 'module' => 'properties'],
            ['name' => 'Edit property address', 'slug' => 'properties.address', 'module' => 'properties'],
            ['name' => 'View team map points', 'slug' => 'maps.team_view', 'module' => 'maps'],
            ['name' => 'Register visit return', 'slug' => 'visits.return', 'module' => 'visits'],
            ['name' => 'Register visit contract', 'slug' => 'visits.contract', 'module' => 'visits'],
            ['name' => 'Change visit status', 'slug' => 'visits.status', 'module' => 'visits'],
            ['name' => 'Export reports', 'slug' => 'reports.export', 'module' => 'reports'],
            ['name' => 'Create campaigns', 'slug' => 'campaigns.create', 'module' => 'campaigns'],
            ['name' => 'Update campaigns', 'slug' => 'campaigns.update', 'module' => 'campaigns'],
            ['name' => 'Close campaigns', 'slug' => 'campaigns.close', 'module' => 'campaigns'],
            ['name' => 'Manage commissions and products', 'slug' => 'commissions.manage', 'module' => 'commissions'],
            ['name' => 'View own commissions', 'slug' => 'commissions.view_self', 'module' => 'commissions'],
            ['name' => 'View customers CRM', 'slug' => 'customers.view', 'module' => 'customers'],
            ['name' => 'Manage customers CRM', 'slug' => 'customers.manage', 'module' => 'customers'],
        ];

        foreach ($permissions as $permission) {
            Permission::query()->updateOrCreate(
                ['slug' => $permission['slug']],
                $permission
            );
        }

        $roles = [
            Role::ADMINISTRATOR => [
                'name' => 'Administrator',
                'description' => 'Acesso total da empresa.',
                'permissions' => [
                    'users.view',
                    'users.manage',
                    'users.create',
                    'users.update',
                    'users.deactivate',
                    'users.reset_password',
                    'users.manage_permissions',
                    'dashboard.view',
                    'dashboard.team',
                    'company.manage',
                    'branding.manage',
                    'onboarding.view',
                    'onboarding.manage',
                    'reports.view',
                    'campaigns.view',
                    'campaigns.manage',
                    'visits.view',
                    'visits.manage',
                    'cities.view',
                    'cities.manage',
                    'sectors.view',
                    'sectors.manage',
                    'properties.view',
                    'properties.manage',
                    'residents.view',
                    'residents.manage',
                    'maps.view',
                    'maps.manage',
                    'sales_app.access',
                    'training.view',
                    'training.manage',
                    'communication.view',
                    'communication.manage',
                    'ai.access',
                    'ai.manage',
                    'billing.view',
                    'billing.manage',
                    'audit.view',
                    'privacy.view',
                    'privacy.manage',
                    'crm.view',
                    'crm.manage',
                    'integrations.view',
                    'integrations.manage',
                    'properties.create',
                    'properties.update',
                    'properties.adjust',
                    'properties.delete',
                    'properties.notes',
                    'properties.address',
                    'maps.team_view',
                    'visits.return',
                    'visits.contract',
                    'visits.status',
                    'reports.export',
                    'campaigns.create',
                    'campaigns.update',
                    'campaigns.close',
                    'commissions.manage',
                    'commissions.view_self',
                    'customers.view',
                    'customers.manage',
                ],
            ],
            Role::MANAGER => [
                'name' => 'Manager',
                'description' => 'Gestão da operação comercial.',
                'permissions' => [
                    'users.view',
                    'users.manage',
                    'users.create',
                    'users.update',
                    'users.deactivate',
                    'users.reset_password',
                    'users.manage_permissions',
                    'dashboard.view',
                    'dashboard.team',
                    'reports.view',
                    'campaigns.view',
                    'campaigns.manage',
                    'visits.view',
                    'visits.manage',
                    'cities.view',
                    'cities.manage',
                    'sectors.view',
                    'sectors.manage',
                    'properties.view',
                    'properties.manage',
                    'residents.view',
                    'residents.manage',
                    'maps.view',
                    'maps.manage',
                    'sales_app.access',
                    'training.view',
                    'training.manage',
                    'communication.view',
                    'communication.manage',
                    'ai.access',
                    'ai.manage',
                    'billing.view',
                    'billing.manage',
                    'audit.view',
                    'privacy.view',
                    'privacy.manage',
                    'onboarding.view',
                    'crm.view',
                    'crm.manage',
                    'integrations.view',
                    'integrations.manage',
                    'properties.create',
                    'properties.update',
                    'properties.adjust',
                    'properties.delete',
                    'properties.notes',
                    'properties.address',
                    'maps.team_view',
                    'visits.return',
                    'visits.contract',
                    'visits.status',
                    'reports.export',
                    'campaigns.create',
                    'campaigns.update',
                    'campaigns.close',
                    'commissions.manage',
                    'commissions.view_self',
                    'customers.view',
                    'customers.manage',
                ],
            ],
            Role::SUPERVISOR => [
                'name' => 'Supervisor',
                'description' => 'Acompanha equipe de campo.',
                'permissions' => [
                    'users.view',
                    'dashboard.view',
                    'dashboard.team',
                    'reports.view',
                    'visits.view',
                    'visits.manage',
                    'cities.view',
                    'sectors.view',
                    'properties.view',
                    'properties.manage',
                    'residents.view',
                    'residents.manage',
                    'maps.view',
                    'maps.team_view',
                    'campaigns.view',
                    'sales_app.access',
                    'training.view',
                    'communication.view',
                    'ai.access',
                    'crm.view',
                    'crm.manage',
                    'properties.create',
                    'properties.update',
                    'properties.adjust',
                    'properties.delete',
                    'properties.notes',
                    'properties.address',
                    'visits.return',
                    'visits.contract',
                    'visits.status',
                    'commissions.manage',
                    'commissions.view_self',
                    'customers.view',
                    'customers.manage',
                ],
            ],
            Role::SELLER => [
                'name' => 'Seller',
                'description' => 'Operação em campo.',
                'permissions' => [
                    'dashboard.view',
                    'visits.view',
                    'visits.manage',
                    'cities.view',
                    'sectors.view',
                    'properties.view',
                    'properties.manage',
                    'residents.view',
                    'residents.manage',
                    'maps.view',
                    'campaigns.view',
                    'sales_app.access',
                    'training.view',
                    'communication.view',
                    'ai.access',
                    'crm.view',
                    'crm.manage',
                    'properties.create',
                    'properties.update',
                    'properties.adjust',
                    'properties.delete',
                    'properties.notes',
                    'properties.address',
                    'visits.return',
                    'visits.contract',
                    'visits.status',
                    'commissions.view_self',
                    'customers.view',
                ],
            ],
            Role::VIEWER => [
                'name' => 'Viewer',
                'description' => 'Somente leitura.',
                'permissions' => [
                    'dashboard.view',
                ],
            ],
            Role::PLATFORM_ADMIN => [
                'name' => 'Platform Admin',
                'description' => 'Administrador da plataforma Expandor (não é papel de empresa cliente).',
                'permissions' => [
                    'platform.access',
                    'platform.companies.manage',
                    'platform.plans.manage',
                    'platform.impersonate',
                    'platform.feature_flags.manage',
                    'platform.health.view',
                ],
            ],
        ];

        foreach ($roles as $slug => $data) {
            $role = Role::query()->updateOrCreate(
                ['slug' => $slug],
                [
                    'name' => $data['name'],
                    'description' => $data['description'],
                ]
            );

            $expected = array_values(array_unique($data['permissions']));
            $permissionIds = Permission::query()
                ->whereIn('slug', $expected)
                ->pluck('id');

            // Guard: sync([]) would DETACH every permission and lock tenants out of /dashboard.
            if ($permissionIds->count() !== count($expected)) {
                $found = Permission::query()->whereIn('slug', $expected)->pluck('slug')->all();
                $missing = array_values(array_diff($expected, $found));

                throw new \RuntimeException(
                    'RolePermissionSeeder refused destructive sync for role ['.$slug.
                    ']: missing permission rows: '.implode(', ', $missing)
                );
            }

            $role->permissions()->sync($permissionIds);
        }
    }
}
